openapi: 3.0.0
info:
  title: Champions League API
  version: 1.0.0
  description: API for managing Champions League data

servers:
  - url: 'http://localhost:8080'

paths:
  /groups:
    get:
      summary: Get all Champions League groups
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChampionsLeagueGroup'

    post:
      summary: Create a new Champions League group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChampionsLeagueGroupInput'
      responses:
        '201':
          description: Group created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChampionsLeagueGroup'

  /groups/{groupName}:
    get:
      summary: Get a specific Champions League group
      parameters:
        - name: groupName
          in: path
          required: true
          description: Group name (A, B, C, or D)
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChampionsLeagueGroup'
        '404':
          description: Group not found

    put:
      summary: Update a specific Champions League group
      parameters:
        - name: groupName
          in: path
          required: true
          description: Group name (A, B, C, or D)
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChampionsLeagueGroupInput'
      responses:
        '200':
          description: Group updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChampionsLeagueGroup'
        '404':
          description: Group not found

    delete:
      summary: Delete a specific Champions League group
      parameters:
        - name: groupName
          in: path
          required: true
          description: Group name (A, B, C, or D)
          schema:
            type: string
      responses:
        '204':
          description: Group deleted successfully
        '404':
          description: Group not found

  /teams:
    get:
      summary: Get all teams
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'

    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamInput'
      responses:
        '201':
          description: Team created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'

  /teams/{teamId}:
    get:
      summary: Get a specific team
      parameters:
        - name: teamId
          in: path
          required: true
          description: Team ID
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '404':
          description: Team not found

    put:
      summary: Update a specific team
      parameters:
        - name: teamId
          in: path
          required: true
          description: Team ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamInput'
      responses:
        '200':
          description: Team updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '404':
          description: Team not found

    delete:
      summary: Delete a specific team
      parameters:
        - name: teamId
          in: path
          required: true
          description: Team ID
          schema:
            type: integer
      responses:
        '204':
          description: Team deleted successfully
        '404':
          description: Team not found

components:
  schemas:
    ChampionsLeagueGroup:
      type: object
      properties:
        groupName:
          type: string
          enum: [A, B, C, D]
        totalPoints:
          type: integer

    ChampionsLeagueGroupInput:
      type: object
      properties:
        totalPoints:
          type: integer

    Team:
      type: object
      properties:
        teamId:
          type: integer
        teamName:
          type: string
        points:
          type: integer
        foundingYear:
          type: integer
        groupName:
          type: string
          enum: [A, B, C, D]

    TeamInput:
      type: object
      properties:
        teamName:
          type: string
        points:
          type: integer
        foundingYear:
          type: integer
        groupName:
          type: string
          enum: [A, B, C, D]